import { icons } from "@/utils/icons";

export const tabs: AppTab[] = [
  { name: "index", title: "Home", icon: icons.home },
  { name: "subscriptions", title: "Subscriptions", icon: icons.wallet },
  { name: "insights", title: "Insights", icon: icons.activity },
  { name: "settings", title: "Settings", icon: icons.setting },
];

const Fonts = {
  figtree: {
    regular: "Figtree-Regular",
    medium: "Figtree-Medium",
    semibold: "Figtree-SemiBold",
    bold: "Figtree-Bold",
  },

  inter: {
    regular: "Inter-Regular",
    medium: "Inter-Medium",
    bold: "Inter-Bold",
  },

  lato: {
    regular: "Lato-Regular",
    bold: "Lato-Bold",
  },

  poppins: {
    regular: "Poppins-Regular",
    medium: "Poppins-Medium",
    bold: "Poppins-Bold",
  },

  roboto: {
    regular: "Roboto-Regular",
    medium: "Roboto-Medium",
    bold: "Roboto-Bold",
  },
};

export default Fonts;

export const chatData = [
  {
    id: "1",
    name: "Rahul Sharma",
    message: "Hey, did you check the latest design?",
    time: "9:00 AM",
    unread: 2,
    src: require("@/assets/images/image-1.jpg"),
  },
  {
    id: "2",
    name: "Priya Patel",
    message: "Meeting rescheduled to 4 PM",
    time: "9:00 AM",
    unread: 0,
    src: require("@/assets/images/image-2.jpg"),
  },
  {
    id: "3",
    name: "Amit Kumar",
    message: "Can you share the report?",
    time: "9:00 AM",
    unread: 1,
    src: require("@/assets/images/image-3.jpg"),
  },
  {
    id: "4",
    name: "Sneha Gupta",
    message: "Thanks for the update!",
    time: "9:00 AM",
    unread: 0,
    src: require("@/assets/images/images.png"),
  },
  {
    id: "5",
    name: "Rahul Sharma",
    message: "Hey, did you check the latest design?",
    time: "9:00 AM",
    unread: 2,
    src: require("@/assets/images/image-1.jpg"),
  },
  {
    id: "6",
    name: "Priya Patel",
    message: "Meeting rescheduled to 4 PM",
    time: "9:00 AM",
    unread: 0,
    src: require("@/assets/images/image-2.jpg"),
  },
  {
    id: "7",
    name: "Amit Kumar",
    message: "Can you share the report?",
    time: "9:00 AM",
    unread: 1,
    src: require("@/assets/images/image-3.jpg"),
  },
  {
    id: "8",
    name: "Sneha Gupta",
    message: "Thanks for the update!",
    time: "9:00 AM",
    unread: 0,
    src: require("@/assets/images/images.png"),
  },
  {
    id: "9",
    name: "Sneha Gupta",
    message: "Thanks for the update!",
    time: "9:00 AM",
    unread: 0,
    src: require("@/assets/images/images.png"),
  },
  {
    id: "10",
    name: "Amit Kumar",
    message: "Can you share the report?",
    time: "9:00 AM",
    unread: 1,
    src: require("@/assets/images/image-3.jpg"),
  },
];

export const callData = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    title: "Product Designer",
    time: "10:30 AM",
    type: "video",
    duration: "12:34",
    missed: false,
    incoming: false,
    avatar: require("@/assets/images/image-1.jpg"),
  },
  {
    id: "2",
    name: "Alex Thompson",
    title: "Frontend Developer",
    time: "Yesterday",
    type: "audio",
    duration: "5:20",
    missed: true,
    incoming: true,
    avatar: require("@/assets/images/image-2.jpg"),
  },
  {
    id: "3",
    name: "Maria Garcia",
    title: "UX Researcher",
    time: "Yesterday",
    type: "video",
    duration: "18:45",
    missed: false,
    incoming: false,
    avatar: require("@/assets/images/image-3.jpg"),
  },
  {
    id: "4",
    name: "James Wilson",
    title: "Project Manager",
    time: "Dec 12, 2024",
    type: "audio",
    duration: "8:15",
    missed: true,
    incoming: true,
    avatar: require("@/assets/images/images.png"),
  },
  {
    id: "5",
    name: "Emily Chen",
    title: "UI Designer",
    time: "Dec 11, 2024",
    type: "video",
    duration: "22:10",
    missed: false,
    incoming: false,
    avatar: require("@/assets/images/image-1.jpg"),
  },
  {
    id: "6",
    name: "Michael Brown",
    title: "Tech Lead",
    time: "Dec 10, 2024",
    type: "audio",
    duration: "3:45",
    missed: false,
    incoming: true,
    avatar: require("@/assets/images/image-2.jpg"),
  },
  {
    id: "7",
    name: "Dr. Sarah Johnson",
    title: "Product Designer",
    time: "10:30 AM",
    type: "video",
    duration: "12:34",
    missed: false,
    incoming: false,
    avatar: require("@/assets/images/image-1.jpg"),
  },
  {
    id: "8",
    name: "Alex Thompson",
    title: "Frontend Developer",
    time: "Yesterday",
    type: "audio",
    duration: "5:20",
    missed: true,
    incoming: true,
    avatar: require("@/assets/images/image-2.jpg"),
  },
  {
    id: "9",
    name: "Maria Garcia",
    title: "UX Researcher",
    time: "Yesterday",
    type: "video",
    duration: "18:45",
    missed: false,
    incoming: false,
    avatar: require("@/assets/images/image-3.jpg"),
  },
  {
    id: "10",
    name: "James Wilson",
    title: "Project Manager",
    time: "Dec 12, 2024",
    type: "audio",
    duration: "8:15",
    missed: true,
    incoming: true,
    avatar: require("@/assets/images/images.png"),
  },
];

export const incomingCalls = [
  // {
  //   id: "1",
  //   name: "Dr. Sarah Johnson",
  //   title: "Product Designer",
  //   avatar: require("@/assets/images/image-1.jpg"),
  //   type: "video",
  //   timestamp: "2 min ago",
  //   priority: "high",
  // },
  // {
  //   id: "2",
  //   name: "Alex Thompson",
  //   title: "Frontend Developer",
  //   avatar: require("@/assets/images/image-2.jpg"),
  //   type: "audio",
  //   timestamp: "15 min ago",
  //   priority: "medium",
  // },
  // {
  //   id: "3",
  //   name: "Maria Garcia",
  //   title: "UX Researcher",
  //   avatar: require("@/assets/images/image-3.jpg"),
  //   type: "video",
  //   timestamp: "1 hour ago",
  //   priority: "low",
  // },
];
